language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "hunnor-dict"
    token:
      secure: "p+0PApWtD8RZ3NWw+Q/ASmSssTTFONi8xgrqWxXAxTBE87ckG43tokiNg9OOqVQXZAwjZZqbctG9SA3/6K9ANzxkBgAUuIEKTDQKMJjZaE44YUuN+8qOthXElkvSSGprbDHqkjx56X7PqX3vqd7VaQYjsVvfyH33CvJg1QSOThqCNQaqHtxw29IegkM5JpueMZTXclBYMwsFmO0UmQ2zcASUctklw0PvKQTwyDK0ao5UQrFOJ4ny9B8/6uOUAkhIZMrkfALs+lBQUbUbP4xAL+GPjxMOk+epTY8NohlC7F1WUF34bq3OrSoG3sbPbUWowQLPNqPlpyyHe3v9Lm3yQHaWDwg+um0qdFS5FC15I2Kl0pqOtGNHas4RsGIrJbdVvKiUcqGhAAhEUt19f3lqUL5qFkld1KlPJiJOUVjuJ/E6W1fbtgy5k3X8hXdxm7SyM1Vt8k81d8c/T26Z1yaBJ/hEq2ClR1rIqd4Obh57GjK4bE/JpLrqONoPrAjZlhq0bzp67lb5tswCBco5TMQUxn5eriZSdzXN0pRwgQITcZZlKTgyTdyiBSgXYmuah5E08je6wc7Jnri9tta3QgBJ1UFuVlvmgk4jUj+5v6RVsb0hIlRh+ennvTKo6NCiS/AvQrtym4a3Lu3z7XL+/XD3OMdDbOCCSYFjP9qRRDlPCOo="
jdk:
  - openjdk13
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
