CREATE TABLE BOYING_GRUPPER (
  BOY_GRUPPE VARCHAR(20) NOT NULL,
  CONSTRAINT PK_BOYING_GRUPPER PRIMARY KEY (BOY_GRUPPE)
);

CREATE TABLE BOYING (
  BOY_NUMMER INT(2) NOT NULL,
  BOY_GRUPPE VARCHAR(20) NOT NULL,
  BOY_TEKST VARCHAR(100) NOT NULL,
  ORDBOK_TEKST VARCHAR(200),
  CONSTRAINT PK_BOYING PRIMARY KEY (BOY_NUMMER, BOY_GRUPPE),
  CONSTRAINT FK_BOYING_BOYING_GRUPPER FOREIGN KEY (BOY_GRUPPE) REFERENCES BOYING_GRUPPER (BOY_GRUPPE)
);

CREATE TABLE PARADIGME (
  PARADIGME_ID VARCHAR(5) NOT NULL,
  BOY_GRUPPE VARCHAR(20) NOT NULL,
  ORDKLASSE VARCHAR(50) NOT NULL,
  ORDKLASSE_UTDYPING VARCHAR(100) DEFAULT NULL,
  FORKLARING VARCHAR(100) DEFAULT NULL,
  DOEME VARCHAR(100) DEFAULT NULL,
  ID INT(5) NOT NULL,
  CONSTRAINT PK_PARADIRME PRIMARY KEY (PARADIGME_ID),
  CONSTRAINT FK_PARADIGME_BOY_GRUPPE FOREIGN KEY (BOY_GRUPPE) REFERENCES BOYING_GRUPPER (BOY_GRUPPE)
);

CREATE TABLE PARADIGME_BOYING (
  PARADIGME_ID VARCHAR(5) NOT NULL,
  BOY_NUMMER INT(2) NOT NULL,
  BOY_GRUPPE VARCHAR(20) NOT NULL,
  BOY_UTTRYKK VARCHAR(50) DEFAULT NULL,
  CONSTRAINT PK_PARADIGME_BOYING PRIMARY KEY (PARADIGME_ID, BOY_NUMMER, BOY_GRUPPE),
  CONSTRAINT FK_PARADIGME_BOYING_PARADIGME FOREIGN KEY (PARADIGME_ID) REFERENCES PARADIGME (PARADIGME_ID),
  CONSTRAINT FK_PARADIGME_BOYING_BOYING FOREIGN KEY (BOY_NUMMER, BOY_GRUPPE) REFERENCES BOYING (BOY_NUMMER, BOY_GRUPPE)
);

CREATE TABLE LEMMA (
  LEMMA_ID INT(8) NOT NULL,
  GRUNNFORM VARCHAR(100) NOT NULL,
  CONSTRAINT PK_LEMMA PRIMARY KEY LEMMA (LEMMA_ID)
);

CREATE TABLE LEMMA_PARADIGME (
  LEMMA_ID INT(8) NOT NULL,
  PARADIGME_ID VARCHAR(5) NOT NULL,
  NORMERING VARCHAR(20) DEFAULT 'normert' NOT NULL,
  FRADATO VARCHAR(10) NOT NULL,
  TILDATO VARCHAR(10) NOT NULL,
  KOMMENTAR VARCHAR(1000),
  CONSTRAINT PK_LEMMA_PARADIGME PRIMARY KEY (LEMMA_ID, PARADIGME_ID),
  CONSTRAINT FK_LEMMA_PARADIGME_LEMMA FOREIGN KEY (LEMMA_ID) REFERENCES LEMMA (LEMMA_ID),
  CONSTRAINT FK_LEMMA_PARADIGME_PARADIGME FOREIGN KEY (PARADIGME_ID) REFERENCES PARADIGME (PARADIGME_ID)
);

CREATE TABLE FULLFORMSLISTE (
  LEMMA_ID INT(8) NOT NULL,
  OPPSLAG VARCHAR(100) NOT NULL,
  TAG VARCHAR(750) NOT NULL,
  PARADIGME_ID VARCHAR(5) NOT NULL,
  BOY_NUMMER INT(2) NOT NULL,
  FRADATO VARCHAR(10) NOT NULL,
  TILDATO VARCHAR(10) NOT NULL,
  NORMERING VARCHAR(100) NOT NULL,
  CONSTRAINT PK_FULLFORMLISTE PRIMARY KEY (LEMMA_ID, OPPSLAG, TAG, PARADIGME_ID, BOY_NUMMER),
  CONSTRAINT FK_FULLFORMLISTE_LEMMA FOREIGN KEY (LEMMA_ID) REFERENCES LEMMA (LEMMA_ID)
);
