CREATE TABLE IF NOT EXISTS HN_HU_ENTRY (
  ENTRY_ID INT(8) NOT NULL,
  POS VARCHAR(25) NOT NULL,
  STATUS INT(2) NOT NULL,
  TRANSLATION VARCHAR(65535) NOT NULL
);

CREATE TABLE IF NOT EXISTS HN_HU_LEMMA (
  LEMMA_ID INT(8) NOT NULL,
  GRUNNFORM VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS HN_HU_ENTRY_LEMMA (
  ENTRY_ID INT(8) NOT NULL,
  LEMMA_ID INT(8) NOT NULL,
  PARADIGME_ID VARCHAR(5),
  BOY_NUMMER INT(2),
  WEIGHT INT(4) NOT NULL,
  SOURCE INT(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS HN_NB_ENTRY (
  ENTRY_ID INT(8) NOT NULL,
  POS VARCHAR(25) NOT NULL,
  STATUS INT(2) NOT NULL,
  TRANSLATION VARCHAR(65535) NOT NULL
);

CREATE INDEX IF NOT EXISTS I_HN_NB_ENTRY_STATUS ON HN_NB_ENTRY(STATUS);

CREATE TABLE IF NOT EXISTS HN_NB_LEMMA (
  LEMMA_ID INT(8) NOT NULL,
  GRUNNFORM VARCHAR(100) NOT NULL
);

CREATE INDEX IF NOT EXISTS I_HN_NB_LEMMA_LEMMA_ID ON HN_NB_LEMMA(LEMMA_ID);

CREATE TABLE IF NOT EXISTS HN_NB_ENTRY_LEMMA (
  ENTRY_ID INT(8) NOT NULL,
  LEMMA_ID INT(8) NOT NULL,
  PARADIGME_ID VARCHAR(5),
  BOY_NUMMER INT(2),
  WEIGHT INT(4) NOT NULL,
  SOURCE INT(2) NOT NULL
);

CREATE INDEX IF NOT EXISTS I_HN_NB_ENTRY_LEMMA_ENTRY_ID ON HN_NB_ENTRY_LEMMA(ENTRY_ID);

CREATE TABLE IF NOT EXISTS HN_NB_LEMMA_PARADIGME (
  LEMMA_ID INT(8) NOT NULL,
  PARADIGME_ID VARCHAR(5) NOT NULL
);

CREATE INDEX IF NOT EXISTS I_HN_NB_LEMMA_PARADIGME_LEMMA_ID ON HN_NB_LEMMA_PARADIGME(LEMMA_ID);
