TRUNCATE TABLE BOYING;
TRUNCATE TABLE BOYING_GRUPPER;
TRUNCATE TABLE FULLFORMSLISTE;
TRUNCATE TABLE LEMMA;
TRUNCATE TABLE LEMMA_PARADIGME;
TRUNCATE TABLE PARADIGME;
TRUNCATE TABLE PARADIGME_BOYING;

INSERT INTO LEMMA (LEMMA_ID, GRUNNFORM) VALUES (10, 'bil');
INSERT INTO LEMMA_PARADIGME (LEMMA_ID, PARADIGME_ID) VALUES (10, '700');

INSERT INTO LEMMA (LEMMA_ID, GRUNNFORM) VALUES (20, 'brannbil');
INSERT INTO LEMMA_PARADIGME (LEMMA_ID, PARADIGME_ID) VALUES (20, '700');
INSERT INTO LEMMA (LEMMA_ID, GRUNNFORM) VALUES (21, 'brannbil');
INSERT INTO LEMMA_PARADIGME (LEMMA_ID, PARADIGME_ID) VALUES (21, '700');

INSERT INTO LEMMA (LEMMA_ID, GRUNNFORM) VALUES (30, 'lastebil');

INSERT INTO LEMMA (LEMMA_ID, GRUNNFORM) VALUES (2522, 'annetstedsfra');
INSERT INTO LEMMA_PARADIGME (LEMMA_ID, PARADIGME_ID) VALUES (2522, '695');
INSERT INTO LEMMA (LEMMA_ID, GRUNNFORM) VALUES (2523, 'annetstedsfra');
INSERT INTO LEMMA_PARADIGME (LEMMA_ID, PARADIGME_ID) VALUES (2523, '695');
